# Generated by Django 2.1 on 2019-07-30 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='权限名称')),
                ('url', models.CharField(blank=True, default='', max_length=100, verbose_name='请求url')),
                ('method', models.IntegerField(choices=[(0, 'POST'), (1, 'GET')], default=0, verbose_name='请求方式')),
                ('detail', models.CharField(blank=True, default='', max_length=200, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Authority', verbose_name='父权限')),
            ],
            options={
                'verbose_name': '权限字典表',
                'verbose_name_plural': '权限字典表',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='角色名称')),
                ('detail', models.CharField(blank=True, default='', max_length=200, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('authority', models.ManyToManyField(blank=True, to='account.Authority', verbose_name='权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True, verbose_name='会员号')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='手机号')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('status', models.IntegerField(blank=True, choices=[(0, '正常'), (1, '暂停')], default=0, null=True, verbose_name='企业用户状态')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('role', models.ManyToManyField(blank=True, to='account.Role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
    ]
