# Generated by Django 2.1 on 2019-07-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, '正常'), (1, '暂停')], default=0, null=True, verbose_name='状态'),
        ),
    ]
